

services:
  app:
    image: node:24-bookworm
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: npm run dev

  jsonserver:
    image: node:24-bookworm
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3090:3090"
    command: npx json-server --watch tools/db/db.json --host 0.0.0.0 -p 3090